name: Release

on:
  push:
    tags:
      - "*"

jobs:
  pypi-publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # This permission is needed for private repositories.
      contents: read
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: pdm-project/setup-pdm@v4

      - name: Publish package distributions to PyPI
        run: pdm publish

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          files: ./dist/*
          name: v${{ github.ref }}
          tag_name: ${{ github.ref }}
